accounts/urls.py
# Django
from django.urls import path

# local Django
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_fun, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.user_sign_out, name='logout'),
    path('admin-logout/', views.admin_sign_out, name='admin-logout')
]

adminpanel/urls.py
# Django
from django.urls import path

# local Django
from .import views

app_name = 'admin-panel'

urlpatterns = [
    path('', views.admin_login, name='admin-login'),
    path('dashbaord/', views.dashboard, name='dashboard'),
    path('add-user/', views.add_user, name='add-user'),
    path('<str:username>/', views.user_profile, name='user-profile'),
    path('update/<str:username>/', views.update_user, name='update-user'),
    path('delete/<str:username>/', views.delete_user, name='delete-user'),
    path('block-user/<int:pk>/', views.block_user, name='block-user'),
    path('unblock_user/<int:pk>/', views.unblock_user, name='unblock-user')
]

user/urls.py
# Django
from django.urls import path

# local Django
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.index, name='index'),
]

userManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('accounts/', include('accounts.urls')),
    path('adminpanel/', include('adminpanel.urls'))
]

templates/includes/messages.html
{% if messages %}
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"></path>
        </symbol>
        <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"></path>
        </symbol>
        <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"></path>
        </symbol>
    </svg>
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:">
                <use xlink:href="#info-fill"></use>
            </svg>
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

templates/includes/navbar.html
<div class="container-fluid bg-dark mb-5">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                {% if request.session.admin %}
                    <a class="navbar-brand" href="{% url 'admin-panel:dashboard' %}">Navbar</a>
                {% else %}
                    <a class="navbar-brand" href="{% url 'user:index' %}">Navbar</a>
                {% endif %}
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarTogglerDemo02"
                        aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item ml-4">
                            {% if request.user.is_superuser %}
                                <a class="nav-link active" aria-current="page" href="{% url 'admin-panel:dashboard' %}">Home</a>
                            {% else %}
                                <a class="nav-link active" aria-current="page" href="{% url 'user:index' %}">Home</a>
                            {% endif %}
                        </li>
                        <li class="nav-item">
                                <form action="{% url 'accounts:admin-logout' %}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" class="nav-link btn btn-sm btn-light" style="color: black"
                                           value="Logout">
                                </form>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>