adminpanel/urls.py
# Django
from django.urls import path

# local Django
from .import views

app_name = 'admin-panel'

urlpatterns = [
    path('', views.admin_login, name='admin-login'),
    path('dashbaord/', views.dashboard, name='dashboard'),
    path('add-user/', views.add_user, name='add-user'),
    path('<str:username>/', views.user_profile, name='user-profile'),
    path('update/<str:username>/', views.update_user, name='update-user'),
    path('delete/<str:username>/', views.delete_user, name='delete-user'),
    path('block-user/<int:pk>/', views.block_user, name='block-user'),
    path('unblock_user/<int:pk>/', views.unblock_user, name='unblock-user')
]

user/urls.py
# Django
from django.urls import path

# local Django
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.index, name='index'),
]

userManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('accounts/', include('accounts.urls')),
    path('adminpanel/', include('adminpanel.urls'))
]

adminpanel/models.py
from django.db import models

# Create your models here.

adminpanel/forms.py
# Django
from django.contrib.auth.models import User
from django import forms


class UpdateUser(forms.ModelForm):
    username = forms.CharField(required=True, max_length=150,
                               widget=forms.TextInput(attrs={'placeholder': 'Enter your username'}),
                               error_messages={'unique': 'User name is already taken, Please choose another one'})
    first_name = forms.CharField(required=True, max_length=150,
                                 widget=forms.TextInput(attrs={'placeholder': 'Enter your first name'}))
    last_name = forms.CharField(required=True, max_length=150,
                                widget=forms.TextInput(attrs={'placeholder': 'Enter your last name'}))
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={'placeholder': 'Enter your email'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

adminpanel/views.py
# Django
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from django.views.decorators.cache import never_cache

# local Django
from .forms import UpdateUser
from .decorators import admin_only
from accounts.forms import CustomUserCreationForm


# Create your views here.


@never_cache
def admin_login(request):
    # if request.user.is_authenticated:
    #     if request.user.is_superuser:
    #         return redirect('admin-panel:dashboard')
    if request.session.has_key('admin'):
        return redirect('admin-panel:dashboard')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        try:
            super_user = User.objects.get(username=username)
            if not super_user.is_superuser:
                messages.error(request, 'You are not admin user')
                return redirect('admin-panel:admin-login')
        except ObjectDoesNotExist:
            pass

        if user is not None:
            request.session['admin'] = 'admin'
            messages.success(request, 'Successfully Logged In')
            return redirect('admin-panel:dashboard')

        messages.error(request, 'Invalid credentials, Please try again.')
    return render(request, 'admin-panel/admin-login.html')


@never_cache
@admin_only
# @login_required(login_url='admin-panel:admin-login')
def dashboard(request):
    users = User.objects.all().order_by('-id')
    context = {
        'users': users
    }
    return render(request, 'admin-panel/dashboard.html', context)


@never_cache
@admin_only
# @login_required(login_url='admin-panel:admin-login')
def user_profile(request, username):
    user = User.objects.get(username=username)
    context = {
        'user': user
    }
    return render(request, 'admin-panel/user-profile.html', context)


@never_cache
@admin_only
# @login_required(login_url='admin-panel:admin-login')
def update_user(request, username):
    user = User.objects.get(username=username)
    form = UpdateUser(instance=user)

    if request.is_ajax():
        form = UpdateUser(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated user profile')
            return JsonResponse({'msg': 'Success'})
        else:
            return JsonResponse({'er': form.errors})
    context = {
            'form': form,
            'username': user.username
    }
    return render(request, 'admin-panel/update-user.html', context)


@never_cache
@admin_only
# @login_required(login_url='admin-panel:admin-login')
def delete_user(request, username):
    try:
        User.objects.get(username=username)
    except ObjectDoesNotExist:
        return redirect('admin-panel:dashboard')

    User.objects.get(username=username).delete()
    messages.success(request, 'Successfully deleted the user')
    return redirect('admin-panel:dashboard')


@never_cache
@admin_only
# @login_required(login_url='admin-panel:admin-login')
def block_user(request, pk):
    user = User.objects.get(id=pk)
    user.is_active = False
    user.save()

    return redirect('admin-panel:dashboard')


@never_cache
@admin_only
# @login_required(login_url='admin-panel:admin-login')
def unblock_user(request, pk):
    user = User.objects.get(id=pk)
    user.is_active = True
    user.save()
    return redirect('admin-panel:dashboard')


@never_cache
@admin_only
# @login_required(login_url='admin-panel:admin-login')
def add_user(request):
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully added an new user.')
            return redirect('admin-panel:dashboard')
    context = {'form': form}
    return render(request, 'admin-panel/add-user.html', context)

templates/admin-panel/add-user.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %} Sign Up {% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
                <div class="col-6 bg-white shadow bg-body rounded mt-5">
                    <div class="text-center mt-4">
                        <h2>Add user</h2>
                    </div>
                    <form action="{% url 'admin-panel:add-user' %}" method="post" class="p-4" id="add-user">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <div class="">
                            <a href="{%url 'admin-panel:dashboard' %}" class="btn btn-primary px-4 mt-4">Back</a>
                            <input type="submit" class="btn btn-primary mt-4 px-4" value="Add User">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $(document).ready(function () {
            $("#add-user").validate({
                rules: {
                    username: {
                        required: true,
                    },
                    first_name: {
                        required: true,
                    },
                    last_name: {
                        required: true,
                    },
                    email: {
                        required: true,
                        email: true
                    },
                    password1: {
                        required: true,
                        minlength: 8,
                    },
                    password2: {
                        required: true,
                        equalTo : "#id_password1"
                    }
                },
            })
        })
    </script>
{% endblock %}

templates/admin-panel/admin-login.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %}
{% block content %}
    <div class="container" id="login">
        <div class="row">
            <div class="col-12">
                <div class="wrapper">
                    <div class="login-box bg-white shadow p-3 mb-5 bg-body rounded">
                        <div class="text-center">
                            <h2>Admin Login</h2>
                        </div>
                        {% include 'includes/messages.html' %}
                        <form class="row g-3" action="{% url 'admin-panel:admin-login' %}" method="post"
                              id="login-form">
                            {% csrf_token %}
                            <div class="col-md-12 py-2">
                                <label for="inputEmail4" class="form-label">Username</label>
                                <input type="text" class="form-control" name="username">
                            </div>
                            <div class="col-md-12">
                                <label for="inputPassword" class="form-label">Password</label>
                                <input type="password" class="form-control" name="password">
                            </div>
                            <div class="col-12 text-center">
                                <input type="submit" class="btn btn-primary w-50" value="Login">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            $("#login-form").validate({
                rules: {
                    username: {
                        required: true,
                    },
                    password: {
                        required: true,
                    },
                }
            })
        })
    </script>
{% endblock %}

templates/admin-panel/dashboard.html
{% extends 'base.html' %}
{% block title %} Dashboard {% endblock %}
{% block style %}
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">
{% endblock %}
{% block content %}
    {% include 'includes/navbar.html' %}
    <div class="container">
        {% include 'includes/messages.html' %}
        <h2>Users list</h2>

        <div class="row">
            <div class="col-12 mt-3">
                <a href="{% url 'admin-panel:add-user' %}" class="btn btn-primary">Add User</a>
            </div>
            <div class="col-12 mt-4 mb-2">
                <table class="table table-striped table-bordered table-hover table-responsive bg-white shadow bg-body rounded"
                       id="myTable">
                    <thead>
                    <tr>
                        <th scope="col">Sl.No</th>
                        <th scope="col">Username</th>
                        <th scope="col">First name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Action</th>
                        <th scope="col">Block / Unblock</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ user.username }}</td>
                            <td>{{ user.first_name | default:'---' }}</td>
                            <td>{{ user.email }}</td>
                            <td class="">
                                <a href="{% url 'admin-panel:user-profile' user.username %}"><span
                                        class="material-icons-outlined text-primary">visibility</span></a>
                                <a href="{% url 'admin-panel:update-user' user.username %}"><span
                                        class="material-icons-outlined text-warning">edit</span></a>
                                {% if not user.is_superuser %}
                                    <a href="#" data-bs-toggle="modal" data-bs-target="#staticBackdrop"><span
                                            class="material-icons-outlined text-danger"
                                            onclick="deleteUser('{{ user.username }}')">delete</span></a>
                                {% endif %}
                            </td>
                            <td>
                                {% if user.is_active %}
                                    {% if not user.is_superuser %}
                                        <a href="#" data-bs-toggle="modal"
                                           data-bs-target="#staticBackdrop" class="btn btn-sm btn-danger"
                                           onclick="blockUser({{ user.id }}, '{{ user.first_name }}')">Block</a>
                                    {% endif %}
                                {% else %}
                                    <a href="#" data-bs-toggle="modal" data-bs-target="#staticBackdrop"
                                       class="btn btn-sm btn-warning"
                                       onclick="unblockUser({{ user.id }}, '{{ user.first_name }}')">Unblock</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
         aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p id="modal-body-content"><span class="text-danger" id="subtext"></span></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a href="" class="btn btn-danger" id="delete">Delete</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });

        function deleteUser(id) {
            document.getElementById("delete").href = '/adminpanel/delete/' + id;
            document.getElementById('staticBackdropLabel').innerText = 'Delete User';
            document.getElementById('delete').innerText = 'Delete';
            document.getElementById('modal-body-content').innerText = 'Are you sure to delete this user, ' + id;
        }

        function blockUser(id, first_name) {
            document.getElementById("delete").href = '/adminpanel/block-user/' + id;
            document.getElementById('staticBackdropLabel').innerText = 'Block User';
            document.getElementById('delete').innerText = 'Block';
            document.getElementById('modal-body-content').innerText = 'Are you sure to block this user , ' + first_name;
        }

        function unblockUser(id, first_name) {
            document.getElementById("delete").href = '/adminpanel/unblock_user/' + id;
            document.getElementById('staticBackdropLabel').innerText = 'Unblock User';
            document.getElementById('delete').innerText = 'Unblock';
            document.getElementById('modal-body-content').innerText = 'Are you sure to unblock this user , ' + first_name;
        }
    </script>
    <script src="//cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
{% endblock %}

templates/admin-panel/search.html
{% extends 'base.html' %}
{% block title %} Dashboard {% endblock %}
{% block content %}
    {% include 'includes/navbar.html' %}
    <div class="container">
        {% include 'includes/messages.html' %}
        <h2>Search results</h2>
        <div class="row">
            <div class="col-12 mt-4 mb-2">
                <table class="table table-striped table-bordered table-hover table-responsive bg-white shadow bg-body rounded">
                    <thead>
                    <tr>
                        <th scope="col">Sl.No</th>
                        <th scope="col">Username</th>
                        <th scope="col">First name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Action</th>
                        <th scope="col">Block / Unblock</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ user.username }}</td>
                            <td>{{ user.first_name | default:'---' }}</td>
                            <td>{{ user.email }}</td>
                            <td class="">
                                <a href="{% url 'admin-panel:user-profile' user.username %}"><span
                                        class="material-icons-outlined text-primary">visibility</span></a>
                                <a href="{% url 'admin-panel:update-user' user.username %}"><span
                                        class="material-icons-outlined text-warning">edit</span></a>
                                <a href="{% url 'admin-panel:delete-user' user.username %}"><span
                                        class="material-icons-outlined text-danger">delete</span></a>
                            </td>
                            <td>
                                {% if user.is_active %}
                                    <a href="{% url 'admin-panel:block-user' user.id %}" class="btn btn-sm btn-danger">Block</a>
                                {% else %}
                                    <a href="{% url 'admin-panel:unblock-user' user.id %}"
                                       class="btn btn-sm btn-warning">Unblock</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% empty %}
                        <p class="text-danger">No records found</p>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/admin-panel/update-user.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %} Update user {% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
                <div class="col-6 bg-white shadow bg-body rounded mt-5">
                    <div class="text-center mt-4">
                        <h2>Update User</h2>
                    </div>
                    <form onsubmit="preventEvent()" class="p-4" id="update" >
                        {% csrf_token %}
                        {{ form | crispy }}
                        <div class="d-flex">
                            <a href="{% url 'admin-panel:dashboard' %}" class="btn btn-primary mt-4 px-4">Cancel</a>
                            <input type="button" class="btn btn-primary mt-4 ms-4 px-4" value="Update" data-bs-toggle="modal"
                                           data-bs-target="#staticBackdrop" onclick="clearModal()">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
         aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Update User</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p id="modal-body-content">Are you sure to update this user</p>
                    <p class="text-danger" id="error-msg"></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button onclick="confirmUpdate( '{{ username }}' )" class="btn btn-warning" id="update-button">Update</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block script %}
    <script>
        $(document).ready(function () {
            $("#update").validate({
                rules: {
                    username: {
                        required: true,
                    },
                    first_name: {
                        required: true,
                    },
                    last_name: {
                        required: true,
                    },
                    email: {
                        required: true,
                        email: true
                    },
                }
            })
        })
        const preventEvent = (e) => {

            e.preventDefault()
        }

        function clearModal() {
             console.log('ff')
            document.getElementById("error-msg").style.display = "None"
            document.getElementById("modal-body-content").style.display = "block"
        }


        function confirmUpdate(id) {

            $.ajax({
                type: 'POST',
                url: '/adminpanel/update/'+id+'/',
                data: $("#update").serialize(),
                dataType: 'json',
                success: function (data) {
                    if (data.msg === 'Success') {
                        window.location.replace("{% url 'admin-panel:dashboard' %}");
                    } else {
                        console.log(data.er['username'][0])
                        document.getElementById("error-msg").style.display = "block"
                        document.getElementById("error-msg").innerHTML = data.er['username'][0]
                        document.getElementById("modal-body-content").style.display = "none"
                    }
                }
            })
        }
    </script>
{% endblock %}

templates/admin-panel/user-profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} User | {{ user.first_name }}  {% endblock %}
{% block content %}
    {% include 'includes/navbar.html' %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6 ">
                <div class="card">
                    <div class="text-center">
                        <img src="{% static 'images/profile.jpeg' %}" class="card-img-top rounded" alt="...">
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-hover table-borderless">
                            <tbody>
                            <tr>
                                <td class="fw-bold">Username:</td>
                                <td>{{ user.username }}</td>
                            </tr>
                            <tr>
                                <td class="fw-bold">First Name:</td>
                                <td>{{ user.first_name }}</td>
                            </tr>
                            <tr>
                                <td class="fw-bold">Last Name:</td>
                                <td>{{ user.last_name }}</td>
                            </tr>
                            <tr>
                                <td class="fw-bold">Email:</td>
                                <td>{{ user.email }}</td>
                            </tr>
                            <tr>
                                <td class="fw-bold">Status:</td>
                                <td>
                                    {% if user.is_active %}
                                        Active User
                                    {% else %}
                                        Blocked User
                                    {% endif %}
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}