accounts/urls.py
# Django
from django.urls import path

# local Django
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_fun, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.user_sign_out, name='logout'),
    path('admin-logout/', views.admin_sign_out, name='admin-logout')
]

adminpanel/urls.py
# Django
from django.urls import path

# local Django
from .import views

app_name = 'admin-panel'

urlpatterns = [
    path('', views.admin_login, name='admin-login'),
    path('dashbaord/', views.dashboard, name='dashboard'),
    path('add-user/', views.add_user, name='add-user'),
    path('<str:username>/', views.user_profile, name='user-profile'),
    path('update/<str:username>/', views.update_user, name='update-user'),
    path('delete/<str:username>/', views.delete_user, name='delete-user'),
    path('block-user/<int:pk>/', views.block_user, name='block-user'),
    path('unblock_user/<int:pk>/', views.unblock_user, name='unblock-user')
]

user/urls.py
# Django
from django.urls import path

# local Django
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.index, name='index'),
]

userManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('accounts/', include('accounts.urls')),
    path('adminpanel/', include('adminpanel.urls'))
]

user/views.py
# Django
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.views.decorators.cache import never_cache


# Create your views here.


@never_cache
def index(request):
    if not request.session.has_key('user'):
        return redirect('accounts:login')

    username = request.session['user']
    user = User.objects.get(username=username)
    print('Username: ', username)

    if not user.is_active:
        del request.session['user']
        return redirect('accounts:login')

    return render(request, 'user/index.html', {'user': user.username})

templates/user/index.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}
{% block content %}
    <div class="container-fluid bg-dark mb-5">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'user:index' %}">Navbar</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarTogglerDemo02"
                            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            <li class="nav-item ml-4">
                                {% if request.user.is_superuser %}
                                    <a class="nav-link active" aria-current="page"
                                       href="{% url 'admin-panel:dashboard' %}">Home</a>
                                {% else %}
                                    <a class="nav-link active" aria-current="page"
                                       href="{% url 'user:index' %}">Home</a>
                                {% endif %}
                            </li>
                            <li class="nav-item">
                                <form action="{% url 'accounts:logout' %}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" class="nav-link btn btn-sm btn-light" style="color: black"
                                           value="Logout">
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <div class="container">
        {% include 'includes/messages.html' %}
        <h2>Welcome, {{ user }}</h2>

    </div>
{% endblock %}